### ISSUE TITLE
Props destructuring

### ISSUE THREAD

**Issue by ale1313** [MaxiGT/NextDots-Exercise#1]
https://github.com/MaxiGT/NextDots-Exercise/blob/8de742daf840a0c06bfbee6d98b29b50db87387d/components/Cocktail.tsx#L13

Basicamente eso, siempre destructura las props y el state en cada componente y screen

**Comment by MaxiGT** [comment]
Javier por algún motivo me sacó el acceso al Slack, ni idea de porque, igualmente, gracias por el issue, lo voy a resolver.

Siempre sirve de ejercicio.
Saludos!
