### ISSUE TITLE
Argument destructuring

### ISSUE THREAD

**Issue by ale1313** [MaxiGT/NextDots-Exercise#3]
https://github.com/MaxiGT/NextDots-Exercise/blob/8de742daf840a0c06bfbee6d98b29b50db87387d/components/DrinksList.tsx#L16

Aca directamente podrias destructurar las propiedades que vas a utilizar en tu flatlist, en este caso item, para asi tener un codigo mas limpio

**Comment by MaxiGT** [comment]
Javier por algún motivo me sacó el acceso al Slack, ni idea de porque, igualmente, gracias por el issue, lo voy a resolver.

Siempre sirve de ejercicio.
Saludos!
