### ISSUE TITLE
No hay manejo de error

### ISSUE THREAD

**Issue by edgarbonillag** [MaxiGT/NextDots-Exercise#5]
https://github.com/MaxiGT/NextDots-Exercise/blob/8de742daf840a0c06bfbee6d98b29b50db87387d/redux/actions/actions.ts#L49

Funciones asíncronas ejecutarlas dentro de un `try catch` y darle manejo a la situación de error. Así mismo, en las posibles actions disparadas en este archivo no hay alguna que maneje cuando haya un error.

Tener en cuenta que el error no sólo puede llegar al catch, sino que también puede venir como objeto en la respuesta de la api

**Comment by MaxiGT** [comment]
Javier por algún motivo me sacó el acceso al Slack, ni idea de porque, igualmente, gracias por el issue, lo voy a resolver.

Siempre sirve de ejercicio.
Saludos!
