### ISSUE TITLE
Falta evaluar otros casos: Cuando hay error o cuando la búsqueda no retorna resultados

### ISSUE THREAD

**Issue by edgarbonillag** [MaxiGT/NextDots-Exercise#6]
https://github.com/MaxiGT/NextDots-Exercise/blob/8de742daf840a0c06bfbee6d98b29b50db87387d/screens/Search.tsx#L29

Se le debe indicar al usuario de manera visual que hay un error en la búsqueda, por ejemplo de conexión o algo.
Así mismo, si la búsqueda no retornó resultados, no se le de be mostrar la pantalla vacía, se le deber decir al user por ejemplo "No hay cocteles que coincidan con tu criterio de búsqueda"

**Comment by MaxiGT** [comment]
Javier por algún motivo me sacó el acceso al Slack, ni idea de porque, igualmente, gracias por el issue, lo voy a resolver.

Siempre sirve de ejercicio.
Saludos!
