### ISSUE TITLE
Manejo óptimo, tomar sólo la data necesaria

### ISSUE THREAD

**Issue by edgarbonillag** [MaxiGT/NextDots-Exercise#7]
Estoy viendo en Postman que cada objeto que llega de la API llega con muchas propiedades y tienes un type definido, con las 3 que necesitas (eso está bien), pero llegan muchas más propiedades que no son necesarias.

Entonces lo ideal es guardar únicamente las que realmente se necesitan. Ejemplo, haciendo un map para construir un array donde cada objeto sea un drink con sólo las 3 propiedades que se necesitan.

Eso no se hace siempre, hay casos en que los campos innecesarios serán 2 o 3, pero como en este caso de verdad son muchos comparado con los necesarios, entonces sí se hace.

Revisar issue #8, ahí se puede hacer el manejo

https://github.com/MaxiGT/NextDots-Exercise/blob/8de742daf840a0c06bfbee6d98b29b50db87387d/redux/actions/actions.ts#L11

**Comment by MaxiGT** [comment]
Agregado un Helper que saca todas aquellas props innecesarias o que no tienen información útil de la data recibida desde la API.
