### ISSUE TITLE
Tomar sólo data necesaria

### ISSUE THREAD

**Issue by edgarbonillag** [MaxiGT/NextDots-Exercise#8]
https://github.com/MaxiGT/NextDots-Exercise/blob/8de742daf840a0c06bfbee6d98b29b50db87387d/redux/actions/actions.ts#L49

Esto está relacionado con el issue #7 de aquí se puede sacar el nuevor array.

**Comment by MaxiGT** [comment]
Agregado Helper para remover data innecesaria o inútil.
