### ISSUE TITLE
[minor] - En el Readme

### ISSUE THREAD

**Issue by edgarbonillag** [MaxiGT/NextDots-Exercise#9]
En Android no existen los Pods jeje Eso es sólo de iOS por los CocoaPods
Después de instalar los modules, en RN 0.61.5 prácticamente ya está todo listo. Ese comando que pones es para hacer el clean y bueno, todo lo demás se hace automáticamente cuando se hace el build cuando se corre la app. Entonces con ese comando no estás instalando de hecho nada jeje

Este issue es sólo para ser preciso en la documentación

**Comment by MaxiGT** [comment]
Javier por algún motivo me sacó el acceso al Slack, ni idea de porque, igualmente, gracias por el issue, lo voy a resolver.

Siempre sirve de ejercicio.
Saludos!

**Comment by MaxiGT** [comment]
Changed / Fixed.
